version: '3.8'

services:
  postgres-master:
    image: postgres:15
    container_name: pg-master
    environment:
      POSTGRES_DB: readwrite_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replica123
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./scripts/master-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./scripts/postgresql-master.conf:/etc/postgresql/postgresql.conf
      - ./scripts/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    command: |
      postgres 
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - postgres-network

  postgres-slave:
    image: postgres:15
    container_name: pg-slave
    environment:
      POSTGRES_DB: readwrite_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGUSER: postgres
      POSTGRES_MASTER_SERVICE: postgres-master
    volumes:
      - ./slave/data:/var/lib/postgresql/data
      - ./scripts/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge