services:
  # MySQL数据库 - 主从模拟方案
  mysql-db:
    image: mysql:8.0
    container_name: mysql-demo
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: readwrite_demo
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - readwrite-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --default-authentication-plugin=mysql_native_password

  # Spring Boot应用
  readwrite-app:
    build: .
    container_name: readwrite-demo
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=readwrite_demo
      - DB_MASTER_USERNAME=master_user
      - DB_MASTER_PASSWORD=master123
      - DB_SLAVE_USERNAME=slave_user
      - DB_SLAVE_PASSWORD=slave123
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - readwrite-network
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  readwrite-network:
    driver: bridge
