version: '3.8'

services:
  # 简化：单Oracle容器，双用户方案
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-demo
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - readwrite-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "sys/OraclePassword123@localhost:1521/XE as sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Spring Boot应用
  readwrite-app:
    build: .
    container_name: readwrite-demo
    environment:
      - SPRING_PROFILES_ACTIVE=shardingsphere
      - DB_MASTER_USERNAME=MASTER_USER
      - DB_MASTER_PASSWORD=master123
      - DB_SLAVE_USERNAME=SLAVE_USER  
      - DB_SLAVE_PASSWORD=slave123
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - readwrite-network
    restart: unless-stopped

volumes:
  oracle-data:

networks:
  readwrite-network:
    driver: bridge