spring:
  application:
    name: readwrite-demo
  
  # ShardingSphere配置 - 只处理读写分离  
  shardingsphere:
    # 数据源配置 - 仅包含master和slave
    datasource:
      names: master,slave
      
      # 主库配置
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/readwrite_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: demo
        password: demo123
        hikari:
          pool-name: MasterHikariPool
          minimum-idle: 5
          maximum-pool-size: 20
          auto-commit: true
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
      
      # 从库配置  
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/readwrite_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: demo
        password: demo123
        hikari:
          pool-name: SlaveHikariPool
          minimum-idle: 5
          maximum-pool-size: 15
          auto-commit: true
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
    
    # 读写分离规则配置
    rules:
      readwrite-splitting:
        data-sources:
          readwrite-ds:
            # 静态读写分离配置
            static-strategy:
              write-data-source-name: master
              read-data-source-names: slave
            # 负载均衡算法
            load-balancer-name: round-robin
        
        # 负载均衡算法配置
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
    
    # 属性配置
    props:
      # 显示SQL
      sql-show: true
      # SQL执行时间阈值(毫秒)，超过阈值的SQL会被记录
      sql-simple: true
      # 最大连接数限制
      max-connections-size-per-query: 1
      # 是否在启动时检查重复表
      check-duplicate-table-enabled: false

  # Baomidou Dynamic DataSource配置 - @DS注解支持
  datasource:
    dynamic:
      # 设置默认的数据源或数据源组，默认值即为 master
      primary: master
      # 是否启用严格模式，默认不启动。启动后在未匹配到指定数据源时候回抛出异常,不启动则使用默认数据源
      strict: false
      datasource:
        # 配置库 - 用于@DS("config")注解
        config:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3308/config_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: config
          password: config123
          hikari:
            pool-name: ConfigHikariPool
            minimum-idle: 5
            maximum-pool-size: 10
            auto-commit: true
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1

server:
  port: 8080
  servlet:
    context-path: /

# 日志配置
logging:
  level:
    com.demo.readwrite: INFO
    org.apache.shardingsphere: INFO
    com.baomidou.dynamic: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n"