spring:
  application:
    name: readwrite-demo
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/readwrite_demo
      username: root
      password: 
server:
  port: 8080
