spring:
  application:
    name: readwrite-demo
  
  # ShardingSphere配置
  shardingsphere:
    # 数据源配置
    datasource:
      names: master,slave
      
      # 主库配置
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
        username: MASTER_USER
        password: master_password
        hikari:
          pool-name: MasterHikariPool
          minimum-idle: 5
          maximum-pool-size: 20
          auto-commit: true
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1 FROM DUAL
      
      # 从库配置  
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
        username: SLAVE_USER
        password: slave_password
        hikari:
          pool-name: SlaveHikariPool
          minimum-idle: 5
          maximum-pool-size: 15
          auto-commit: true
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1 FROM DUAL
    
    # 读写分离规则配置
    rules:
      readwrite-splitting:
        data-sources:
          readwrite-ds:
            # 静态读写分离配置
            static-strategy:
              write-data-source-name: master
              read-data-source-names: slave
            # 负载均衡算法
            load-balancer-name: round-robin
        
        # 负载均衡算法配置
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
    
    # 属性配置
    props:
      # 显示SQL
      sql-show: true
      # SQL执行时间阈值(毫秒)，超过阈值的SQL会被记录
      sql-simple: true
      # 最大连接数限制
      max-connections-size-per-query: 1
      # 是否在启动时检查重复表
      check-duplicate-table-enabled: false

server:
  port: 8080
  servlet:
    context-path: /api

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.readwrite.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.demo.readwrite: INFO
    org.apache.shardingsphere: INFO
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n"