spring:
  application:
    name: readwrite-demo
  
  # PostgreSQL主从数据源配置
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/readwrite_demo
      username: postgres
      password: postgres123
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: MasterHikariPool
        maximum-pool-size: 10
        minimum-idle: 5
        
    slave:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5433/readwrite_demo
      username: postgres
      password: postgres123
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: SlaveHikariPool
        maximum-pool-size: 10
        minimum-idle: 5

# 日志配置
logging:
  level:
    com.demo.readwrite: DEBUG
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{50}] - %msg%n"

server:
  port: 8080